### ISSUE TITLE
port forwarding to wrong IP

### ISSUE THREAD

**Issue by abigchopstick** [allenn/er-ss#3]
现在的PORT FORWARD方案会被转发到SS服务器的IP而不是路由真实的IP

由于远程的SS服务器不可控，这样PORT FORWARD就会失败显示不成功，请问有什么办法可以让PORT FORWARD找到真实的WAN口IP吗？

canyouseeme.org这个网站是很多国外软件判断PORTFORWARD是否成功的一个网站，可以把他加入chinadns的白名单吗？

**Comment by allenn** [comment]
chinadns的白名单是可以自己添加的

**Comment by allenn** [comment]
我没太明白你说的转发失败是什么意思

**Comment by abigchopstick** [comment]
嗯，只是连接的网站的PORT扫描成SS服务器的PORT而不是本机IP，现在已经明白是怎么回事了，谢谢。
